wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    code_path: code/main.py
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.12
    start_time: 1657606245
    t:
      1:
      - 1
      - 5
      - 9
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.9.12
      5: 0.12.16
      8:
      - 2
      - 5
