wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-Adam
      5: 1
      6:
      - 1
    - 1: Train/Loss_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.9.12
    start_time: 1657607508
    t:
      1:
      - 1
      - 5
      - 9
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.9.12
      5: 0.12.16
      8:
      - 2
      - 5
args/NMS_threshold:
  desc: null
  value: 0.0
args/NMS_window:
  desc: null
  value: 6
args/Post_norm:
  desc: null
  value: false
args/SoccerNet_path:
  desc: null
  value: /hdda/Datasets/SoccerNet
args/accelerator:
  desc: null
  value: gpu
args/batch_size:
  desc: null
  value: 134
args/benchmark:
  desc: null
  value: true
args/check_val_every_n_epoch:
  desc: null
  value: 1
args/ckpt_path:
  desc: null
  value: None
args/criterion:
  desc: null
  value: BCELoss
args/detect_anomaly:
  desc: null
  value: true
args/deterministic:
  desc: null
  value: true
args/devices:
  desc: null
  value: -1
args/dropout:
  desc: null
  value: 0.0
args/entity:
  desc: null
  value: cihe-cis
args/experiment_name:
  desc: null
  value: Baseline
args/fast_dev:
  desc: null
  value: false
args/fast_dev_run:
  desc: null
  value: false
args/feature_dim:
  desc: null
  value: None
args/features:
  desc: null
  value: baidu_soccer_embeddings.npy
args/framerate:
  desc: null
  value: 1
args/limit_val_batches:
  desc: null
  value: 1.0
args/log_every_n_steps:
  desc: null
  value: 10
args/logger:
  desc: null
  value: wandb
args/lr:
  desc: null
  value: 0.0001
args/lrE:
  desc: null
  value: 1.0e-08
args/masking_epoch:
  desc: null
  value: 0
args/masking_ratio:
  desc: null
  value: 0.0
args/max_epochs:
  desc: null
  value: 100
args/max_iters:
  desc: null
  value: 125
args/max_num_worker:
  desc: null
  value: 6
args/min_epochs:
  desc: null
  value: 1
args/model_name:
  desc: null
  value: TwinsSVT_1d_group_LoGlo_SE
args/patience:
  desc: null
  value: 5
args/peg_kernel_size:
  desc: null
  value: 9
args/precision:
  desc: null
  value: 32
args/profiler:
  desc: null
  value: None
args/project:
  desc: null
  value: MixSaT
args/reload_dataloaders_every_n_epochs:
  desc: null
  value: 100
args/s1_depth:
  desc: null
  value: 1
args/s1_global_k:
  desc: null
  value: 20
args/s1_local_patch_size:
  desc: null
  value: 16
args/s1_next_dim:
  desc: null
  value: 60
args/s1_patch_size:
  desc: null
  value: 8
args/s2_depth:
  desc: null
  value: 2
args/s2_global_k:
  desc: null
  value: 20
args/s2_local_patch_size:
  desc: null
  value: 4
args/s2_next_dim:
  desc: null
  value: 720
args/s2_patch_size:
  desc: null
  value: 4
args/seed:
  desc: null
  value: 42
args/split_test:
  desc: null
  value:
  - test
  - challenge
args/split_train:
  desc: null
  value:
  - train
args/split_valid:
  desc: null
  value:
  - valid
args/strategy:
  desc: null
  value: ddp
args/sync_batchnorm:
  desc: null
  value: true
args/test_only:
  desc: null
  value: false
args/version:
  desc: null
  value: 2
args/warmup:
  desc: null
  value: 125
args/weight:
  desc: null
  value: None
args/weight_decay:
  desc: null
  value: 0.0
args/window_shift:
  desc: null
  value: 0
args/window_size:
  desc: null
  value: 3
args/window_stride:
  desc: null
  value: 0
